"""update user table

Revision ID: 947f50c56cd4
Revises: 39f35844fcc7
Create Date: 2023-04-25 17:47:51.372278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947f50c56cd4'
down_revision = '39f35844fcc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
